# Continuous Integration configuration with gitlab.com
# See https://gitlab.com/help/ci/yaml/README.md

stages:
  - gen
  - build
  - test
  - build-others
  - analyses

.docker-job: &docker_job
  tags:
    - docker
    - linux
  # only:
  #   - master

###
# Generation jobs
###

generation:
  <<: *docker_job
  stage: gen
  image: com2.systerel.fr:5000/c765/gen-ext@sha256:b303ef8934eb99d3023243d05129a463b3f25be310cc1d6e1ea7abd621695465  # gen-ext:1.0
  script:
    - ./.pre-build-ext.sh
  artifacts:
    name: 'bgenc-${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}'
    paths:
      - 'address_space_generation/genc'
      - 'csrc/services/bgenc'
    expire_in: '1 month'

###
# Compilation jobs
###

.build-linux: &build_linux
  <<: *docker_job
  stage: build
  image: registry.gitlab.com/systerel/s2opc/build@sha256:8e139a7e9077ef150639b7d772e2b6caf41a34c9c10d97d194140c2588665c81  # build:1.3
  script:
    - &build_command_line './build.sh && cd $BUILD_DIR && cmake --build . --target install && ../tests/scripts/make-ctestfile-relative CTestTestfile.cmake > ../bin/CTestTestfile.cmake'
  variables: &build_linux_variables
    CMAKE_INSTALL_PREFIX: '../install_linux64'
    DOCKER_IMAGE: 'sha256:e6ef818bf9d8a244afdf2558bac405719a2b73ca1e154de635502988ab48f49c'
    BUILD_DIR: build
  artifacts:
    name: 'bin-${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}'
    paths:
      - 'bin/'
      - 'install_linux64/'
      - 'build/'  # Required when using coverage analysis
    expire_in: '1 month'

# Used by "normal" pipeline
build-linux64-ASan:
  <<: *build_linux
  variables:
    <<: *build_linux_variables
    WITH_ASAN: 1
  except:
    variables:
      - $NO_ASAN

# Used by coverage
build-linux64:
  <<: *build_linux
  only:
    variables:
      - $WITH_COVERAGE
      - $CROSS_COMPILE

build-win64: &build_win64
  <<: *docker_job
  stage: build-others
  image: registry.gitlab.com/systerel/s2opc/mingw_build@sha256:749abd06fac07c9fbc3e3e4b2dd18ff5e3c974371d1a2094252432ea6fe2d6af  # mingw_build:1.3
  script:
    - *build_command_line
    - 'echo $CI_JOB_ID > ../job.txt'
  variables: &build_win64_variables
    CMAKE_INSTALL_PREFIX: '../install_win64'
    CMAKE_TOOLCHAIN_FILE: 'toolchain-mingw32-w64_x86_64.cmake'
    DOCKER_IMAGE: 'sha256:ed2d22733470f050c03edc72f5ff68a364c392523599df5661337f689f19516d'
    BUILD_SHARED_LIBS: 'true'
    BUILD_DIR: build_toolchain
  artifacts:
    name: 'bin-w64-${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}'
    paths:
      - 'bin/'
      - 'install_win64/'
      - 'job.txt'
    expire_in: '1 month'
  only:
    variables:
      - $CROSS_COMPILE
      - $WINDOWS_TEST
  dependencies:
    - generation

build-win32:
  <<: *build_win64
  variables:
    <<: *build_win64_variables
    CMAKE_INSTALL_PREFIX: '../install_win32'
    CMAKE_TOOLCHAIN_FILE: 'toolchain-mingw32-w64.cmake'
  artifacts:
    name: 'bin-w32-${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}'
    paths:
      - 'bin/'
      - 'install_win32/'
    expire_in: '1 month'
  only:
    variables:
      - $CROSS_COMPILE

###
# Test jobs
###

.test-linux: &test_linux
  <<: *docker_job
  stage: test
  except:
    variables:
      - $NO_ASAN

# Test check belongs to the test part, however it does not depend on linux build.
test-check:
  <<: *test_linux
  image: registry.gitlab.com/systerel/s2opc/check@sha256:76e11aaf485bdbbb8f48bc75d5e423370b9c71b0842f3b35de41f85c8aa21530  # check:1.0
  script:
    - ./.check-code.sh
  dependencies:
    - generation

test-unit:
  <<: *test_linux
  image: registry.gitlab.com/systerel/s2opc/test@sha256:e10957c4e1ea14cc2c1fe2d8b8eec4e923d85cc9c168e6aebe3418eaec4b8ace  # test:2.1
  script:
    - ./test-all.sh
  artifacts:
    name: 'test-unit-results-${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}'
    paths:
      - 'bin/*.tap'
      - 'bin/*.log'
      - 'bin/Testing'
      - 'build/'
    when: always
    expire_in: '1 month'
  except:
    variables:
      - $CROSS_COMPILE
      - $WINDOWS_TEST

test-uactt:
  <<: *test_linux
  image: com2.systerel.fr:5000/c765/uactt@sha256:baf2dd81823abe2b4c5777f7a80b1357812c6e4d52c69e295a476630cc2086d7  # uactt:1.0
  script:
    - 'cd acceptances_tests/ && ./launch_acceptance_tests.sh'
  artifacts:
    name: 'uactt-logs-${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}'
    paths:
      - 'bin/*.tap'
      - 'bin/*.log'
    when: on_failure
    expire_in: '1 month'

###
# Analysis jobs
###

coverage-analysis:
  <<: *docker_job
  stage: analyses
  image: registry.gitlab.com/systerel/s2opc/test@sha256:e10957c4e1ea14cc2c1fe2d8b8eec4e923d85cc9c168e6aebe3418eaec4b8ace  # test:2.1
  script:
    - ./.gen_coverage.sh
  artifacts:
    name: 'coverage-report-${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}'
    paths:
      - 'report'
    expire_in: '1 month'
  only:
    variables:
      - $WITH_COVERAGE

.windows-appveyor:
  stage: analyses
  script:
    - 'export JOB_ID=$(cat job.txt)'
    - 'echo $JOB_ID'
    - 'curl -H "Authorization: Bearer $APPVEYOR_TOKEN" -H "Content-Type: application/json" --request POST -d ''{"accountName" : "Systerel", "projectSlug": "s2opc", "branch": "''$CI_COMMIT_REF_NAME''", "environmentVariables": {"JOB_ID": "''$JOB_ID''"}}'' https://ci.appveyor.com/api/builds'
  tags:
    - linux
