# Continuous Integration configuration with gitlab.com
# See https://gitlab.com/help/ci/yaml/README.md

stages:
  - gen
  - build
  - test
  - build-others
  - analyses

.docker-job: &docker_job
  tags:
    - docker
    - linux
  # only:
  #   - master

###
# Generation jobs
###

generation:
  <<: *docker_job
  stage: gen
  image: com2.systerel.fr:5000/c765/gen-ext@sha256:b303ef8934eb99d3023243d05129a463b3f25be310cc1d6e1ea7abd621695465  # gen-ext:1.0
  script:
    - ./.pre-build-ext.sh
  artifacts:
    name: 'bgenc-${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}'
    paths:
      - 'csrc/services/bgenc'
    expire_in: '1 month'

###
# Compilation jobs
###

.build-linux: &build_linux
  <<: *docker_job
  stage: build
  image: registry.gitlab.com/systerel/s2opc/build@sha256:043994ffeee40e86c17f30a1bd9adb00817fed52a84494112e939bf43c55d116 # build:1.7
  script:
    - &build_command_line './build.sh && cd $BUILD_DIR && cmake --build . --target install && ../tests/scripts/make-ctestfile-relative CTestTestfile.cmake > ../bin/CTestTestfile.cmake'
  variables: &build_linux_variables
    CMAKE_INSTALL_PREFIX: '../install_linux64'
    DOCKER_IMAGE: 'sha256:3feedb6f6402c061637c968dfa6ea92cb25235a229f1b5c886989ae2065b1dc8'
    BUILD_DIR: build
  artifacts:
    name: 'bin-${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}'
    paths:
      - 'bin/'
      - 'install_linux64/'
      - 'build/'  # Required when using coverage analysis
    expire_in: '1 month'

# Used by "normal" pipeline
build-linux64-ASan:
  <<: *build_linux
  variables:
    <<: *build_linux_variables
    WITH_ASAN: 1
  except:
    variables:
      - $NO_ASAN

# Used by coverage
build-linux64:
  <<: *build_linux
  only:
    variables:
      - $WITH_COVERAGE
      - $CROSS_COMPILE

build-win64: &build_win64
  <<: *docker_job
  stage: build-others
  image: registry.gitlab.com/systerel/s2opc/mingw_build@sha256:cac97f3e32fd3aced5de8109529432a7a1cd31f8b28e6d3246599c234cd245d1  # mingw_build:1.4
  script:
    - *build_command_line
    - 'echo $CI_JOB_ID > ../job.txt'
  variables: &build_win64_variables
    CMAKE_INSTALL_PREFIX: '../install_win64'
    CMAKE_TOOLCHAIN_FILE: 'toolchain-mingw32-w64_x86_64.cmake'
    DOCKER_IMAGE: 'sha256:ed2d22733470f050c03edc72f5ff68a364c392523599df5661337f689f19516d'
    BUILD_SHARED_LIBS: 'true'
    BUILD_DIR: build_toolchain
  artifacts:
    name: 'bin-w64-${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}'
    paths:
      - 'bin/'
      - 'install_win64/'
      - 'job.txt'
    expire_in: '1 month'
  only:
    variables:
      - $CROSS_COMPILE
      - $WINDOWS_TEST
  dependencies:
    - generation

build-win32:
  <<: *build_win64
  variables:
    <<: *build_win64_variables
    CMAKE_INSTALL_PREFIX: '../install_win32'
    CMAKE_TOOLCHAIN_FILE: 'toolchain-mingw32-w64.cmake'
  artifacts:
    name: 'bin-w32-${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}'
    paths:
      - 'bin/'
      - 'install_win32/'
    expire_in: '1 month'
  only:
    variables:
      - $CROSS_COMPILE

# Used by coverity, also starts the analysis
build-linux64-coverity:
  <<: *docker_job
  stage: build
  image: registry.gitlab.com/systerel/s2opc/coverity@sha256:96ff1f104be2fe36c1fe6b9f1154b192fda811db1826d03568a6e31a29ff5fda # 1.0
  script: |-
    mkdir build
    cd build
    cmake -DCMAKE_BUILD_TYPE=Debug ..
    /opt/cov-analysis-linux64-2017.07/bin/cov-build --dir cov-int make
    tar czf cov-int.tar.gz cov-int
    curl -k --form token=${COVERITY_TOKEN} --form email=${COVERITY_EMAIL} --form version=${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA} --form description=${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA} --form file=@cov-int.tar.gz https://scan.coverity.com/builds?project=S2OPC
  only:
    variables:
      - $WITH_COVERITY

###
# Test jobs
###

.test-linux: &test_linux
  <<: *docker_job
  stage: test
  except:
    variables:
      - $NO_ASAN

# Test check belongs to the test part, however it does not depend on linux build.
test-check:
  <<: *test_linux
  image: registry.gitlab.com/systerel/s2opc/check@sha256:71b37ed9ed70d3ac67ceb1b92c691ad9c7cb943112dd5edc328d7cbde8fa5ed6  # check:1.1
  script:
    - ./.check-code.sh
  dependencies:
    - generation
  artifacts:
    name: 'test-check-results-${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}'
    paths:
      - 'pre-build-check.log'
      - 'clang_tidy.log'
    when: on_failure
    expire_in: '1 month'

test-unit:
  <<: *test_linux
  image: registry.gitlab.com/systerel/s2opc/test@sha256:2517f830aa2dbf50868021cf184981c5b75f91b1768e4fbfdab282cc0daa8231  # test:2.3
  script:
    - ./test-all.sh
  artifacts:
    name: 'test-unit-results-${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}'
    paths:
      - 'bin/*.tap'
      - 'bin/*.log'
      - 'bin/Testing'
      - 'build/'
    when: always
    expire_in: '1 month'
  except:
    variables:
      - $CROSS_COMPILE
      - $WINDOWS_TEST
      - $WITH_COVERITY

test-uactt:
  <<: *test_linux
  image: com2.systerel.fr:5000/c765/uactt@sha256:86b9712edeb458df08980c651b8adfdc150de4d89731d98ae74c05e8bc501d2f  # uactt:1.4
  script:
    - 'cd acceptances_tests/ && ./launch_acceptance_tests.sh'
  artifacts:
    name: 'uactt-logs-${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}'
    paths:
      - 'bin/*.tap'
      - 'bin/*.log'
    when: on_failure
    expire_in: '1 month'

###
# Analysis jobs
###

coverage-analysis:
  <<: *docker_job
  stage: analyses
  image: registry.gitlab.com/systerel/s2opc/test@sha256:2517f830aa2dbf50868021cf184981c5b75f91b1768e4fbfdab282cc0daa8231  # test:2.3
  script:
    - ./.gen_coverage.sh
  artifacts:
    name: 'coverage-report-${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}'
    paths:
      - 'report'
    expire_in: '1 month'
  only:
    variables:
      - $WITH_COVERAGE

windows-appveyor:
  stage: analyses
  script:
    - 'export JOB_ID=$(cat job.txt)'
    - 'echo $JOB_ID'
    - 'curl -H "Authorization: Bearer $APPVEYOR_TOKEN" -H "Content-Type: application/json" --request POST -d ''{"accountName" : "Systerel", "projectSlug": "s2opc", "branch": "''$CI_COMMIT_REF_NAME''", "environmentVariables": {"JOB_ID": "''$JOB_ID''"}}'' https://ci.appveyor.com/api/builds'
  tags:
    - linux
  only:
    variables:
      - $WINDOWS_TEST
